name: CI - Run tests

on:
  push: {}
  pull_request: {}

jobs:
  test-lib:
    name: Test lib
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8 --activate

      - name: Install root deps
        run: pnpm install --no-frozen-lockfile

      - name: Install lib deps
        run: |
          cd lib
          pnpm install --no-frozen-lockfile

      - name: Run lib tests
        run: |
          cd lib
          pnpm test


  test-backend:
    name: Test backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8 --activate

      - name: Install root deps
        run: pnpm install --no-frozen-lockfile

      - name: Install backend deps
        run: |
          cd Backend
          pnpm install --no-frozen-lockfile

      - name: Run backend tests
        run: |
          pnpm build:lib
          cd Backend
          pnpm test
